### ISSUE TITLE
pypyodbc hangs with pypy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsyaim/pypyodbc#34]
```
I think we had this problem before.   pypyodbc can connect and work OK with 
cPython but using a nightly pypy snapshot, I'm getting a hang.   Ctrl-C below 
illusrtates the stack trace where it's stopped.


Python 2.7.3 (2f0d7dced731, Jan 11 2014, 23:29:24)
[PyPy 2.3.0-alpha0 with GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] 
on darwin
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``PyPy 1.3 awaiting release''
>>>> import pypyodbc
>>>> pypyodbc.connect(uid='scott', pwd='tiger', dsn='ms_2005')
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/src/pypyodbc/trunk/pypyodbc/pypyodbc.py", line 2259, in __init__
    self.connect(connectString, autocommit, ansi, timeout, unicode_results, readonly)
  File "/usr/local/src/pypyodbc/trunk/pypyodbc/pypyodbc.py", line 2307, in connect
    check_success(self, ret)
  File "/usr/local/src/pypyodbc/trunk/pypyodbc/pypyodbc.py", line 930, in check_success
    ctrl_err(SQL_HANDLE_DBC, ODBC_obj.dbc_h, ret, ODBC_obj.ansi)
  File "/usr/local/src/pypyodbc/trunk/pypyodbc/pypyodbc.py", line 891, in ctrl_err
    NativeError, Message, len(Message), ADDR(Buffer_len))
  File "/usr/local/src/pypy-zeek/lib_pypy/_ctypes/function.py", line 707, in __call__
    result = self._call_funcptr(funcptr, *args)
  File "/usr/local/src/pypy-zeek/lib_pypy/_ctypes/function.py", line 370, in _call_funcptr
    result = funcptr(*newargs)
KeyboardInterrupt

```

Original issue reported on code.google.com by `zzz...@gmail.com` on 12 Jan 2014 at 1:07

**Comment by GoogleCodeExporter** [comment]
```
for reference, my previous issue here was #20 which has been resolved.
```

Original comment by `zzz...@gmail.com` on 12 Jan 2014 at 1:14

**Comment by GoogleCodeExporter** [comment]
```
I noticed the pypyodbc.py you were using was an old version, can you try the 
attached version, which is a version soon will be released, and the difference 
is enhanced performance
```

Original comment by `jiangwen...@gmail.com` on 19 Jan 2014 at 9:08
- Changed state: **Started**

Attachments:
- [pypyodbc.py](https://storage.googleapis.com/google-code-attachments/pypyodbc/issue-34/comment-2/pypyodbc.py)

**Comment by GoogleCodeExporter** [comment]
```
does that work?
```

Original comment by `jiangwen...@gmail.com` on 26 Jan 2014 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
havent' tried yet.   its in my short list of things to do, maybe i can get to 
it tomorrow night!
```

Original comment by `zzz...@gmail.com` on 26 Jan 2014 at 5:05

**Comment by GoogleCodeExporter** [comment]
```
that one connects.   you might want to note here what the issue actually is 
which that file resolves.
```

Original comment by `zzz...@gmail.com` on 28 Jan 2014 at 12:11

**Comment by GoogleCodeExporter** [comment]
```
Actually the current version already fixed that problem. Looks like you were 
using an old version that had the problem.
```

Original comment by `jiangwen...@gmail.com` on 1 Feb 2014 at 3:54
- Changed state: **Fixed**
