### ISSUE TITLE
Sage Line 100 Odbc connect KO

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsyaim/pypyodbc#61]
```
What steps will reproduce the problem?
Sage Line 100 (Retrieve Database)
import pypyodbc
self.cnxn = pypyodbc.connect(r'DRIVER={SAGE Gestion Commerciale 
100};DSN=myDsnSource;uid=myuser;pwd=mypwd')

3.

What is the expected output? What do you see instead?
Expected output > Connection Established

Instead:
Traceback (most recent call last):
  File "C:\python\sage\test.py", line 23, in <module>
    self.cnxn = pypyodbc.connect(r'DRIVER={SAGE Gestion Commerciale 100};DSN=sageUserSource;uid=myuser;pwd=mypwd')
  File "C:\Python34\lib\site-packages\pypyodbc.py", line 2434, in __init__
    self.connect(connectString, autocommit, ansi, timeout, unicode_results, readonly)
  File "C:\Python34\lib\site-packages\pypyodbc.py", line 2483, in connect
    check_success(self, ret)
  File "C:\Python34\lib\site-packages\pypyodbc.py", line 988, in check_success
    ctrl_err(SQL_HANDLE_DBC, ODBC_obj.dbc_h, ret, ODBC_obj.ansi)
  File "C:\Python34\lib\site-packages\pypyodbc.py", line 966, in ctrl_err
    raise DatabaseError(state,err_text)
pypyodbc.DatabaseError: ('S1000', '[S1000] [Simba][SimbaEngine ODBC Driver][DRM 
File Library]Dossier non ouvert\xa0!')

<class 'pypyodbc.DatabaseError'>

What version of the product are you using? On what operating system?
pypyodbc : 1.3.3
python : 3.4
Sage Line 100 : 16.05


I'm trying to connect to sage 100 with the odbc driver.
I try with a DSN, fileDSN and user source system.

With php or ODBC Query Tool 1.38 the connection works well.
So, did you have any idea to fix my issue ?

Thank you in advance

```

Original issue reported on code.google.com by `jul...@cableorganizer.fr` on 15 Jan 2015 at 1:33

**Comment by GoogleCodeExporter** [comment]
```
Is it possible to specify two DBQ files ?
```

Original comment by `jul...@cableorganizer.fr` on 15 Jan 2015 at 1:34
